// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using waitingList.Data;

#nullable disable

namespace waitingList.Migrations
{
    [DbContext(typeof(WaitingListDbContext))]
    [Migration("20260828102208_AddQueueCheckIn")]
    partial class AddQueueCheckIn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("waitingList.Models.Client", b =>
                {
                    b.Property<Guid>("clientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("accNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("cellNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("clientId");

                    b.HasIndex("accNumber")
                        .IsUnique();

                    b.ToTable("clients");
                });

            modelBuilder.Entity("waitingList.Models.QueueEntry", b =>
                {
                    b.Property<Guid>("queueEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("centreId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("joinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("queueDate")
                        .HasColumnType("date");

                    b.Property<int>("queueNumber")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("visitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("queueEntryId");

                    b.HasIndex("visitId")
                        .IsUnique();

                    b.HasIndex("centreId", "queueDate", "queueNumber")
                        .IsUnique();

                    b.ToTable("queueEntries");
                });

            modelBuilder.Entity("waitingList.Models.UnitCentre", b =>
                {
                    b.Property<int>("centreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("centreId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("allowedRadiusMetres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(150);

                    b.Property<string>("centreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("externalCentreId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("lastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("centreId");

                    b.HasIndex("externalCentreId")
                        .IsUnique();

                    b.ToTable("unitCentres");
                });

            modelBuilder.Entity("waitingList.Models.Visit", b =>
                {
                    b.Property<Guid>("visitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("cancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("centreId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("checkedInAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("clientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("qrGeneratedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("qrToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("visitDate")
                        .HasColumnType("date");

                    b.HasKey("visitId");

                    b.HasIndex("centreId");

                    b.HasIndex("qrToken")
                        .IsUnique();

                    b.HasIndex("clientId", "centreId", "visitDate")
                        .IsUnique();

                    b.ToTable("visits");
                });

            modelBuilder.Entity("waitingList.Models.QueueEntry", b =>
                {
                    b.HasOne("waitingList.Models.UnitCentre", "centre")
                        .WithMany("queueEntries")
                        .HasForeignKey("centreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("waitingList.Models.Visit", "visit")
                        .WithOne("queueEntry")
                        .HasForeignKey("waitingList.Models.QueueEntry", "visitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("centre");

                    b.Navigation("visit");
                });

            modelBuilder.Entity("waitingList.Models.Visit", b =>
                {
                    b.HasOne("waitingList.Models.UnitCentre", "centre")
                        .WithMany("visits")
                        .HasForeignKey("centreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("waitingList.Models.Client", "client")
                        .WithMany("visits")
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("centre");

                    b.Navigation("client");
                });

            modelBuilder.Entity("waitingList.Models.Client", b =>
                {
                    b.Navigation("visits");
                });

            modelBuilder.Entity("waitingList.Models.UnitCentre", b =>
                {
                    b.Navigation("queueEntries");

                    b.Navigation("visits");
                });

            modelBuilder.Entity("waitingList.Models.Visit", b =>
                {
                    b.Navigation("queueEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
